---
federation:
  inbound:
    service-id-mapping:
    - from: "jfrou@*"
      to: "jfrou@01f5bhjskb16ng3ehv4wcagdqy"
    - from: "jfmd@*"
      to: "jfmd@01f5bhjtpq8tywevbnz97yaa58"
    - from: "jfrt@*"
      to: "jfrt@01f5bhppehsyjh146jttnz0vf9"
    - from: "jfevt@*"
      to: "jfevt@01f5bhj5gq3xnp1sjvxtsj1phx"
    - from: "jffe@*"
      to: "jffe@000"
licenses:
- server-name: "0583781c1360"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TVMw\r\
    \nd05pMHdPVlF4TnpveU1qb3hOeTR4TWpSYUNtbGtPaUF3WlRkbU9UY3hOaTFrWmpRNExUUmhNRFF0\r\
    \nT1dZd1lTMWtOVFEwTXpobE1tSm1ZVGNLYjNkdVpYSTZJRlJ5YVdWa0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpFdE1EVXRNVEJVTVRjNk1qSTZNVGN1TVRJMFdnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogZHZWeEVHc2g5dmJJWEhneldqdXNJTDZqVHd6TGR2TGZ2aXF1djFKWUFvbUxSckVY\r\
    \nb3N3MURJRFFrTW1WVjh2R0hBY3NJQVZROWM2WWhvcDVETGJIT1ZTZ1Jnb20xZk1ZcEJLODFHWWFG\r\
    \ncXJoZW5JRFZUUXE2dUViZ054cUlQbmw2Ny9mZVdYTjhaYlZYTms0L3ZuTXB0T1pscG9xaHZXTTlN\r\
    \neWxWbWcweUxmZG1qeVlqeW1uSHdXYURuMU1rd3dMeUdMbDNYekZXdTdZR1NCd2Zkb2NSOUFnUDJI\r\
    \nQndVWGVrZGRoMFJobXY0Witja1U3bTYvRDZMK2ZVYkcveitsa28wbGFXUmlOZ2NaZEoyUHZYNUZY\r\
    \nb2JXaCt6RFRZTGVXZG5ldktlY2M1WFkyeUFBRHQvOHcyYXk1ZjNzUm9Hai9DMDRtMElqV01DRnpz\r\
    \nYXYzb0dPSTR3PT0KdmVyc2lvbjogMQo=\r\n"
- server-name: "13fb8aa6a471"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TVMw\r\
    \nd05pMHdPVlF4TnpveU1qb3hOeTR4TWpSYUNtbGtPaUF3WlRkbU9UY3hOaTFrWmpRNExUUmhNRFF0\r\
    \nT1dZd1lTMWtOVFEwTXpobE1tSm1ZVGNLYjNkdVpYSTZJRlJ5YVdWa0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpFdE1EVXRNVEJVTVRjNk1qSTZNVGN1TVRJMFdnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogZHZWeEVHc2g5dmJJWEhneldqdXNJTDZqVHd6TGR2TGZ2aXF1djFKWUFvbUxSckVY\r\
    \nb3N3MURJRFFrTW1WVjh2R0hBY3NJQVZROWM2WWhvcDVETGJIT1ZTZ1Jnb20xZk1ZcEJLODFHWWFG\r\
    \ncXJoZW5JRFZUUXE2dUViZ054cUlQbmw2Ny9mZVdYTjhaYlZYTms0L3ZuTXB0T1pscG9xaHZXTTlN\r\
    \neWxWbWcweUxmZG1qeVlqeW1uSHdXYURuMU1rd3dMeUdMbDNYekZXdTdZR1NCd2Zkb2NSOUFnUDJI\r\
    \nQndVWGVrZGRoMFJobXY0Witja1U3bTYvRDZMK2ZVYkcveitsa28wbGFXUmlOZ2NaZEoyUHZYNUZY\r\
    \nb2JXaCt6RFRZTGVXZG5ldktlY2M1WFkyeUFBRHQvOHcyYXk1ZjNzUm9Hai9DMDRtMElqV01DRnpz\r\
    \nYXYzb0dPSTR3PT0KdmVyc2lvbjogMQo=\r\n"
- server-name: "61374378fe65"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TVMw\r\
    \nd05pMHdPVlF4TnpveU1qb3hOeTR4TWpSYUNtbGtPaUF3WlRkbU9UY3hOaTFrWmpRNExUUmhNRFF0\r\
    \nT1dZd1lTMWtOVFEwTXpobE1tSm1ZVGNLYjNkdVpYSTZJRlJ5YVdWa0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpFdE1EVXRNVEJVTVRjNk1qSTZNVGN1TVRJMFdnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogZHZWeEVHc2g5dmJJWEhneldqdXNJTDZqVHd6TGR2TGZ2aXF1djFKWUFvbUxSckVY\r\
    \nb3N3MURJRFFrTW1WVjh2R0hBY3NJQVZROWM2WWhvcDVETGJIT1ZTZ1Jnb20xZk1ZcEJLODFHWWFG\r\
    \ncXJoZW5JRFZUUXE2dUViZ054cUlQbmw2Ny9mZVdYTjhaYlZYTms0L3ZuTXB0T1pscG9xaHZXTTlN\r\
    \neWxWbWcweUxmZG1qeVlqeW1uSHdXYURuMU1rd3dMeUdMbDNYekZXdTdZR1NCd2Zkb2NSOUFnUDJI\r\
    \nQndVWGVrZGRoMFJobXY0Witja1U3bTYvRDZMK2ZVYkcveitsa28wbGFXUmlOZ2NaZEoyUHZYNUZY\r\
    \nb2JXaCt6RFRZTGVXZG5ldktlY2M1WFkyeUFBRHQvOHcyYXk1ZjNzUm9Hai9DMDRtMElqV01DRnpz\r\
    \nYXYzb0dPSTR3PT0KdmVyc2lvbjogMQo=\r\n"
- server-name: "45c7f3ec8f24"
  key: "cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TVMw\r\
    \nd05pMHdPVlF4TnpveU1qb3hOeTR4TWpSYUNtbGtPaUF3WlRkbU9UY3hOaTFrWmpRNExUUmhNRFF0\r\
    \nT1dZd1lTMWtOVFEwTXpobE1tSm1ZVGNLYjNkdVpYSTZJRlJ5YVdWa0NuQnliM0JsY25ScFpYTTZJ\r\
    \nSHQ5Q25OcFoyNWhkSFZ5WlRvZ2JuVnNiQXAwY21saGJEb2dkSEoxWlFwMGVYQmxPaUJVVWtsQlRB\r\
    \ncDJZV3hwWkVaeWIyMDZJREl3TWpFdE1EVXRNVEJVTVRjNk1qSTZNVGN1TVRJMFdnbz0KICAgIHNp\r\
    \nZ25hdHVyZTogZHZWeEVHc2g5dmJJWEhneldqdXNJTDZqVHd6TGR2TGZ2aXF1djFKWUFvbUxSckVY\r\
    \nb3N3MURJRFFrTW1WVjh2R0hBY3NJQVZROWM2WWhvcDVETGJIT1ZTZ1Jnb20xZk1ZcEJLODFHWWFG\r\
    \ncXJoZW5JRFZUUXE2dUViZ054cUlQbmw2Ny9mZVdYTjhaYlZYTms0L3ZuTXB0T1pscG9xaHZXTTlN\r\
    \neWxWbWcweUxmZG1qeVlqeW1uSHdXYURuMU1rd3dMeUdMbDNYekZXdTdZR1NCd2Zkb2NSOUFnUDJI\r\
    \nQndVWGVrZGRoMFJobXY0Witja1U3bTYvRDZMK2ZVYkcveitsa28wbGFXUmlOZ2NaZEoyUHZYNUZY\r\
    \nb2JXaCt6RFRZTGVXZG5ldktlY2M1WFkyeUFBRHQvOHcyYXk1ZjNzUm9Hai9DMDRtMElqV01DRnpz\r\
    \nYXYzb0dPSTR3PT0KdmVyc2lvbjogMQo=\r\n"
schema-version: 2
